language: go

go:
  - 1.8
  - 1.9

sudo: required

env:
  global:
    - ES_VERSION=5.6.3

before_install:
  - curl -O https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-${ES_VERSION}.deb
  - sudo dpkg -i --force-confnew elasticsearch-${ES_VERSION}.deb
  - sudo service elasticsearch start

install:
  - make build
  - cp config.yaml.sample config.yaml

before_script:
  - until curl --silent -XGET --fail http://localhost:9200; do printf '.'; sleep 1; done

script:
  - make ARGS="-tags=travis" test
