language: go

go:
  - 1.7

sudo: required

env:
  global:
    - ES_VERSION=2.4.6

before_install:
  - curl -O https://download.elastic.co/elasticsearch/release/org/elasticsearch/distribution/deb/elasticsearch/${ES_VERSION}/elasticsearch-${ES_VERSION}.deb
  - sudo dpkg -i --force-confnew elasticsearch-${ES_VERSION}.deb
  - sudo service elasticsearch start

install:
  - make build
  - cp config.yaml.sample config.yaml

before_script:
  - until curl --silent -XGET --fail http://localhost:9200; do printf '.'; sleep 1; done

script:
  - make ARGS="-tags=travis" test
